# Generated by Django 5.0.6 on 2024-06-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_escuela_ramo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='id_escuela',
            field=models.AutoField(db_column='idEscuela ', primary_key=True, serialize=False),
        ),
    ]
